from enum import Enum

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

TILE_SIZE = int(((SCREEN_WIDTH / 42) + (SCREEN_HEIGHT / 24)) // 2)
TILE_DIM = (TILE_SIZE, TILE_SIZE)
MAX_NUM_TILES = 10

GRID_COL = MAX_NUM_TILES
GRID_ROW = 20 + MAX_NUM_TILES

GRID_BUFFER_ROW = MAX_NUM_TILES
GRID_PLAYFIELD_ROW = GRID_ROW - GRID_BUFFER_ROW

GRID_WIDTH = GRID_COL * TILE_SIZE
GRID_HEIGHT = GRID_ROW * TILE_SIZE
GRID_PLAYFIELD_HEIGHT = GRID_HEIGHT - (GRID_BUFFER_ROW * TILE_SIZE)
GRID_BUFFER_HEIGHT = GRID_HEIGHT - (GRID_PLAYFIELD_ROW * TILE_SIZE)

GRID_OFFSET_X = (SCREEN_WIDTH // 2) - (GRID_WIDTH // 2)
GRID_OFFSET_Y = ((SCREEN_HEIGHT - GRID_PLAYFIELD_HEIGHT) // 2) - GRID_BUFFER_HEIGHT

PREVIEW_SIZE = TILE_SIZE * 2

LIVE_TIME = 1000
COMBO_MULT = 0.2
PYLYO_SCORE = 50


class Move(Enum):
    UP = 0
    DOWN = 1
    LEFT = 2
    RIGHT = 3


CLASSIC_PIECES = {
    "I": [[0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0]],
    "J": [[1, 0, 0], [1, 1, 1], [0, 0, 0]],
    "L": [[0, 0, 1], [1, 1, 1], [0, 0, 0]],
    "O": [[1, 1], [1, 1]],
    "S": [[0, 1, 1], [1, 1, 0], [0, 0, 0]],
    "Z": [[1, 1, 0], [0, 1, 1], [0, 0, 0]],
    "T": [[0, 1, 0], [1, 1, 1], [0, 0, 0]],
}

CLASSIC_COLORS = {
    "I": "#009EA8",
    "J": "#0C00A8",
    "L": "#A85300",
    "O": "#A8A600",
    "S": "#A80000",
    "Z": "#00A804",
    "T": "#5F00A8",
}
